set shell := ["nu", "-c"]

# Building
TARGET := "riscv64gc-unknown-none-elf"
KERNEL_ELF := "target"/TARGET/"release"/"os"
KERNEL_BIN := KERNEL_ELF + ".bin"

# BOARD
BOARD := "qemu"
SBI := "rustsbi"
BOOTLOADER := ".."/"bootloader"/SBI + "-" + BOARD + ".bin"

# KERNEL ENTRY
KERNEL_ENTRY_PA := "0x80200000"

# Binutils
OBJDUMP := "rust-objdump --arch-name=riscv64"
OBJCOPY := "rust-objcopy --binary-architecture=riscv64"

build: kernel
	{{OBJCOPY}} {{KERNEL_ELF}} --strip-all -O binary {{KERNEL_BIN}}

kernel:
	echo Platform: {{BOARD}}
	cargo build --release

run: build
    qemu-system-riscv64 -machine virt -nographic -bios {{BOOTLOADER}} -device loader,file={{KERNEL_BIN}},addr={{KERNEL_ENTRY_PA}}